In [1]:
import numpy as np
import random

In [2]:
array1=np.random.rand(2,3,5)
print(array1)

[[[0.0218989  0.8501336  0.73714034 0.70336949 0.02074336]
  [0.43227665 0.77993666 0.20988175 0.89559377 0.70141366]
  [0.56864494 0.97364023 0.55988105 0.82008983 0.89036842]]

 [[0.12596015 0.56559029 0.39366209 0.75415269 0.5126871 ]
  [0.38610168 0.09660863 0.72759761 0.95595106 0.59771729]
  [0.84085928 0.5544991  0.47093548 0.48907183 0.76878434]]]


In [6]:
array2=np.random.randint(0,10,size=(2,3,5))
print(array2)

[[[9 4 9 3 1]
  [7 8 7 2 0]
  [6 5 7 4 4]]

 [[3 4 0 1 1]
  [1 0 2 6 0]
  [5 3 4 0 2]]]


In [9]:
b=np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
print(array1.size,b.size)


30 30


In [21]:
c=b.reshape((2,3,5))

In [22]:
d=array1+c

In [24]:
print(array1)

[[[0.0218989  0.8501336  0.73714034 0.70336949 0.02074336]
  [0.43227665 0.77993666 0.20988175 0.89559377 0.70141366]
  [0.56864494 0.97364023 0.55988105 0.82008983 0.89036842]]

 [[0.12596015 0.56559029 0.39366209 0.75415269 0.5126871 ]
  [0.38610168 0.09660863 0.72759761 0.95595106 0.59771729]
  [0.84085928 0.5544991  0.47093548 0.48907183 0.76878434]]]


In [25]:
print(d)

[[[1.0218989  1.8501336  1.73714034 1.70336949 1.02074336]
  [1.43227665 1.77993666 1.20988175 1.89559377 1.70141366]
  [1.56864494 1.97364023 1.55988105 1.82008983 1.89036842]]

 [[1.12596015 1.56559029 1.39366209 1.75415269 1.5126871 ]
  [1.38610168 1.09660863 1.72759761 1.95595106 1.59771729]
  [1.84085928 1.5544991  1.47093548 1.48907183 1.76878434]]]


In [26]:
e=array1*d

In [27]:
d_min=d.min()
print(d_min)
d_max=d.max()
print(d_max)
d_mean=d.mean()
print(d_mean)

1.0207433563866606
1.9736402280226502
1.5801730418512558


In [28]:
f=np.empty(shape=[2,3,5],dtype=int)

In [29]:
print(f)

[[[7 0 1 2 4]
  [2 9 4 1 6]
  [7 4 9 1 3]]

 [[1 5 5 1 9]
  [9 7 4 8 8]
  [3 9 4 9 9]]]


In [34]:
"""For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. 
If a value equals to d_mean, assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f
for d_min in d. Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the 
following values: 0, 25, 50, 75, and 100.
"""

for x in range(d.shape[0]):
    for y in range (d.shape[1]):
        for z in range (d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z]=25
            elif d[x,y,z]> d_mean and d[x,y,z] < d_max:
                f[x,y,z]=75
            elif d[x,y,z]== d_mean:
                f[x,y,z]=50
            elif d[x,y,z]== d_min:
                f[x,y,z]= 0
            else:
                f[x,y,z]=100
                
print(f)

[[[ 25  75  75  75   0]
  [ 25  75  25  75  75]
  [ 25 100  25  75  75]]

 [[ 25  25  25  75  25]
  [ 25  25  75  75  75]
  [ 75  25  25  25  75]]]
